/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package javaapplication1;

import javax.swing.JOptionPane;
import java.awt.Color;
import java.util.Random;

import java.util.Timer;
import java.util.TimerTask;
import javax.security.auth.x500.X500Principal;

/**
 *
 * @author Mitch Justin
 */
public class tictactoe extends javax.swing.JFrame {
 
int player;
int p1score=0;
int p2score=0; 

Random rand= new Random();


static int second =0;
static int minute=0;
static int hour=0;
static int milliseconds=0;

static boolean state = true;

    /**
     * Creates new form tictactoe
     */
    public tictactoe() {
        initComponents();
      
                }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel4 = new javax.swing.JPanel();
        BTN1 = new javax.swing.JButton();
        BTN2 = new javax.swing.JButton();
        BTN3 = new javax.swing.JButton();
        BTN4 = new javax.swing.JButton();
        BTN5 = new javax.swing.JButton();
        BTN6 = new javax.swing.JButton();
        BTN7 = new javax.swing.JButton();
        BTN9 = new javax.swing.JButton();
        BTN8 = new javax.swing.JButton();
        BTN10 = new javax.swing.JButton();
        BTN11 = new javax.swing.JButton();
        BTN12 = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jSeparator1 = new javax.swing.JSeparator();
        lblplayer1score = new javax.swing.JTextField();
        lblplayer2score = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel3 = new javax.swing.JPanel();
        exit = new javax.swing.JToggleButton();
        newgame = new javax.swing.JButton();
        clearscore = new javax.swing.JButton();
        hours = new javax.swing.JLabel();
        seconds = new javax.swing.JLabel();
        minutes = new javax.swing.JLabel();
        millisecond = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        CLEAR = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(0, 255, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        jPanel4.setBackground(new java.awt.Color(51, 102, 0));

        BTN1.setBackground(new java.awt.Color(51, 255, 0));
        BTN1.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN1.setForeground(new java.awt.Color(255, 255, 255));
        BTN1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN1ActionPerformed(evt);
            }
        });

        BTN2.setBackground(new java.awt.Color(51, 255, 0));
        BTN2.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN2.setForeground(new java.awt.Color(255, 255, 255));
        BTN2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN2ActionPerformed(evt);
            }
        });

        BTN3.setBackground(new java.awt.Color(51, 255, 0));
        BTN3.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN3.setForeground(new java.awt.Color(255, 255, 255));
        BTN3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN3ActionPerformed(evt);
            }
        });

        BTN4.setBackground(new java.awt.Color(51, 255, 0));
        BTN4.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN4.setForeground(new java.awt.Color(255, 255, 255));
        BTN4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN4ActionPerformed(evt);
            }
        });

        BTN5.setBackground(new java.awt.Color(51, 255, 0));
        BTN5.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN5.setForeground(new java.awt.Color(255, 255, 255));
        BTN5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN5ActionPerformed(evt);
            }
        });

        BTN6.setBackground(new java.awt.Color(51, 255, 0));
        BTN6.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN6.setForeground(new java.awt.Color(255, 255, 255));
        BTN6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN6ActionPerformed(evt);
            }
        });

        BTN7.setBackground(new java.awt.Color(51, 255, 0));
        BTN7.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN7.setForeground(new java.awt.Color(255, 255, 255));
        BTN7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN7ActionPerformed(evt);
            }
        });

        BTN9.setBackground(new java.awt.Color(51, 255, 0));
        BTN9.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN9.setForeground(new java.awt.Color(255, 255, 255));
        BTN9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN9ActionPerformed(evt);
            }
        });

        BTN8.setBackground(new java.awt.Color(51, 255, 0));
        BTN8.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN8.setForeground(new java.awt.Color(255, 255, 255));
        BTN8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN8ActionPerformed(evt);
            }
        });

        BTN10.setBackground(new java.awt.Color(51, 255, 0));
        BTN10.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN10.setForeground(new java.awt.Color(255, 255, 255));
        BTN10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN10ActionPerformed(evt);
            }
        });

        BTN11.setBackground(new java.awt.Color(51, 255, 0));
        BTN11.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN11.setForeground(new java.awt.Color(255, 255, 255));
        BTN11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN11ActionPerformed(evt);
            }
        });

        BTN12.setBackground(new java.awt.Color(51, 255, 0));
        BTN12.setFont(new java.awt.Font("Segoe UI", 1, 30)); // NOI18N
        BTN12.setForeground(new java.awt.Color(255, 255, 255));
        BTN12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTN12ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BTN10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addComponent(BTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(BTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(46, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN1, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN2, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN3, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN4, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN5, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN6, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(BTN7, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN8, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN9, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(BTN11, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(BTN12, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(17, Short.MAX_VALUE))
        );

        jPanel2.setBackground(new java.awt.Color(51, 153, 0));

        jLabel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("PLAYER 1:");

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("PLAYER 2:");

        lblplayer1score.setBackground(new java.awt.Color(51, 153, 0));
        lblplayer1score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblplayer1scoreActionPerformed(evt);
            }
        });

        lblplayer2score.setBackground(new java.awt.Color(51, 153, 0));
        lblplayer2score.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                lblplayer2scoreActionPerformed(evt);
            }
        });

        jLabel3.setFont(new java.awt.Font("Microsoft PhagsPa", 1, 14)); // NOI18N
        jLabel3.setText("SCORE LIST");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSeparator1)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel2)
                                .addGap(18, 18, 18)
                                .addComponent(lblplayer2score, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(18, 18, 18)
                                .addComponent(lblplayer1score, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(51, 51, 51)
                        .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 97, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(51, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(13, 13, 13)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(lblplayer1score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 3, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(10, 10, 10)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(lblplayer2score, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(45, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        exit.setBackground(new java.awt.Color(255, 255, 255));
        exit.setForeground(new java.awt.Color(0, 0, 0));
        exit.setText("X");
        exit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                exitMouseClicked(evt);
            }
        });

        newgame.setBackground(new java.awt.Color(255, 255, 153));
        newgame.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        newgame.setForeground(new java.awt.Color(255, 255, 255));
        newgame.setText("NEW GAME");
        newgame.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                newgameMouseClicked(evt);
            }
        });
        newgame.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                newgameActionPerformed(evt);
            }
        });

        clearscore.setBackground(new java.awt.Color(255, 255, 153));
        clearscore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        clearscore.setForeground(new java.awt.Color(255, 255, 255));
        clearscore.setText("RESET");
        clearscore.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                clearscoreMouseClicked(evt);
            }
        });
        clearscore.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                clearscoreActionPerformed(evt);
            }
        });

        hours.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        hours.setText("00:");

        seconds.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        seconds.setText("00:");

        minutes.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        minutes.setText("00:");

        millisecond.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N

        jLabel4.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("TIC TAC TOE");

        jLabel5.setText("PLAYER1-X");

        jLabel6.setText("PLAYER2-O");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(41, Short.MAX_VALUE)
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 292, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(15, 15, 15))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel6)
                .addGap(96, 96, 96))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6)))
        );

        CLEAR.setBackground(new java.awt.Color(255, 255, 153));
        CLEAR.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        CLEAR.setForeground(new java.awt.Color(255, 255, 255));
        CLEAR.setText("CLEAR");
        CLEAR.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                CLEARMouseClicked(evt);
            }
        });
        CLEAR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                CLEARActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(24, 24, 24)
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(newgame, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(clearscore, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE)
                            .addComponent(CLEAR, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 125, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(millisecond, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(60, 60, 60))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)))
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(45, 45, 45)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(hours, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(seconds, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(minutes, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(millisecond, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(26, 26, 26)
                        .addComponent(clearscore, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(CLEAR, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(newgame, javax.swing.GroupLayout.PREFERRED_SIZE, 40, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void clearscoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_clearscoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_clearscoreActionPerformed

    private void clearscoreMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_clearscoreMouseClicked
          BTN1.setText("");
        BTN1.setBackground(Color.GREEN);
        BTN2.setText("");
        BTN2.setBackground(Color.GREEN);
        BTN3.setText("");
        BTN3.setBackground(Color.GREEN);
        BTN4.setText("");
        BTN4.setBackground(Color.GREEN);
        BTN5.setText("");
        BTN5.setBackground(Color.GREEN);
        BTN6.setText("");
        BTN6.setBackground(Color.GREEN);
        BTN7.setText("");
        BTN7.setBackground(Color.GREEN);
        BTN8.setText("");
        BTN8.setBackground(Color.GREEN);
        BTN9.setText("");
        BTN9.setBackground(Color.GREEN);
        BTN10.setText("");
        BTN10.setBackground(Color.GREEN);
        BTN11.setText("");
        BTN11.setBackground(Color.GREEN);
        BTN12.setText("");
        BTN12.setBackground(Color.GREEN);
        
        lblplayer1score.setText("");
        lblplayer2score.setText("");
        player=0;
        p1score=0;
        p2score=0;
        
     
        
        // TODO add your handling code here:
    }//GEN-LAST:event_clearscoreMouseClicked

    private void lblplayer2scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblplayer2scoreActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_lblplayer2scoreActionPerformed

    private void lblplayer1scoreActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_lblplayer1scoreActionPerformed
        String p1score=Float.toString(player);
        lblplayer1score.setText(p1score);        // TODO add your handling code here:
    }//GEN-LAST:event_lblplayer1scoreActionPerformed

    private void newgameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_newgameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_newgameActionPerformed

    private void newgameMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_newgameMouseClicked
        BTN1.setText("");
        BTN1.setBackground(Color.GREEN);
        BTN2.setText("");
        BTN2.setBackground(Color.GREEN);
        BTN3.setText("");
        BTN3.setBackground(Color.GREEN);
        BTN4.setText("");
        BTN4.setBackground(Color.GREEN);
        BTN5.setText("");
        BTN5.setBackground(Color.GREEN);
        BTN6.setText("");
        BTN6.setBackground(Color.GREEN);
        BTN7.setText("");
        BTN7.setBackground(Color.GREEN);
        BTN8.setText("");
        BTN8.setBackground(Color.GREEN);
        BTN9.setText("");
        BTN9.setBackground(Color.GREEN);
        BTN10.setText("");
        BTN10.setBackground(Color.GREEN);
        BTN11.setText("");
        BTN11.setBackground(Color.GREEN);
        BTN12.setText("");
        BTN12.setBackground(Color.GREEN);
    
        
         state = false;
        second=0;
        minute=0;
        hour=0;
        milliseconds=0;
       
        
        
        hours.setText("00 : ");
         minutes.setText("00 : ");
          seconds.setText("00 : ");
          millisecond.setText("00");
        
    player=0;
    p1score=0;
    p2score=0;
    lblplayer1score.setText("");
    lblplayer2score.setText("");
    }//GEN-LAST:event_newgameMouseClicked

    private void exitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_exitMouseClicked
        int exit = JOptionPane.showConfirmDialog(null,"You sure you want to exit","Conformation",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

        if(exit == JOptionPane.YES_OPTION){
            this.dispose();
        }
    }//GEN-LAST:event_exitMouseClicked

    private void BTN9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN9ActionPerformed
        if(BTN9.getText().isEmpty()){
            if (player == 1){
                BTN9.setText("O");
                BTN9.disable();
                BTN9.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN9.setText("X");
                BTN9.disable();
                BTN9.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN9ActionPerformed

    private void BTN7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN7ActionPerformed
        if(BTN7.getText().isEmpty()){
            if (player == 1){
                BTN7.setText("O");
                BTN7.disable();
                BTN7.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN7.setText("X");
                BTN7.disable();
                BTN7.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN7ActionPerformed

    private void BTN6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN6ActionPerformed
        if(BTN6.getText().isEmpty()){
            if (player == 1){
                BTN6.setText("O");
                BTN6.disable();
                BTN6.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN6.setText("X");
                BTN6.disable();
                BTN6.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN6ActionPerformed

    private void BTN5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN5ActionPerformed
        if(BTN5.getText().isEmpty()){
            if (player == 1){
                BTN5.setText("O");
                BTN5.disable();
                BTN5.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN5.setText("X");
                BTN5.disable();
                BTN5.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN5ActionPerformed

    private void BTN4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN4ActionPerformed
        if(BTN4.getText().isEmpty()){
            if (player == 1){
                BTN4.setText("O");
                BTN4.disable();
                BTN4.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN4.setText("X");
                BTN4.disable();
                BTN4.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN4ActionPerformed

    private void BTN3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN3ActionPerformed
        if(BTN3.getText().isEmpty()){
            if (player == 1){
                BTN3.setText("O");
                BTN3.disable();
                BTN3.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN3.setText("X");
                BTN3.disable();
                Winner();
                BTN3.setBackground(Color.blue);
                player=1;
            }
        }              // TODO add your handling code here:
    }//GEN-LAST:event_BTN3ActionPerformed

    private void BTN2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN2ActionPerformed
        if(BTN2.getText().isEmpty()){
            if (player == 1){
                BTN2.setText("O");
                BTN2.disable();
                BTN2.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN2.setText("X");
                BTN2.disable();
                BTN2.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }              // TODO add your handling code here:
    }//GEN-LAST:event_BTN2ActionPerformed

    private void BTN12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN12ActionPerformed
        if(BTN12.getText().isEmpty()){
            if (player == 1){
                BTN12.setText("O");
                BTN12.disable();
                BTN12.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN12.setText("X");
                BTN12.disable();
                Winner();
                BTN12.setBackground(Color.blue);
                player=1;
            }
        }            // TODO add your handling code here: ---------------------------------------------------------------------------------------------------------------------------------------------------------------
    }//GEN-LAST:event_BTN12ActionPerformed

    private void BTN1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN1ActionPerformed
        if(BTN1.getText().isEmpty()){
            if (player == 1){
                BTN1.setText("O");
                BTN1.disable();
                BTN1.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN1.setText("X");
                BTN1.disable();
                BTN1.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }        // TODO add your handling code here:
    }//GEN-LAST:event_BTN1ActionPerformed

    private void BTN11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN11ActionPerformed
        if(BTN11.getText().isEmpty()){
            if (player == 1){
                BTN11.setText("O");
                BTN11.disable();
                BTN11.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN11.setText("X");
                BTN11.disable();
                BTN11.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN11ActionPerformed

    private void BTN10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN10ActionPerformed
        if(BTN10.getText().isEmpty()){
            if (player == 1){
                BTN10.setText("O");
                BTN10.disable();
                BTN10.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN10.setText("X");
                BTN10.disable();
                BTN10.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN10ActionPerformed

    private void BTN8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTN8ActionPerformed
        if(BTN8.getText().isEmpty()){
            if (player == 1){
                BTN8.setText("O");
                BTN8.disable();
                BTN8.setBackground(Color.red);
                Winner();
                player=2;
            }
            else {
                BTN8.setText("X");
                BTN8.disable();
                BTN8.setBackground(Color.blue);
                Winner();
                player=1;
            }
        }            // TODO add your handling code here:
    }//GEN-LAST:event_BTN8ActionPerformed

    private void CLEARMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_CLEARMouseClicked
  BTN1.setText("");
        BTN1.setBackground(Color.GREEN);
        BTN2.setText("");
        BTN2.setBackground(Color.GREEN);
        BTN3.setText("");
        BTN3.setBackground(Color.GREEN);
        BTN4.setText("");
        BTN4.setBackground(Color.GREEN);
        BTN5.setText("");
        BTN5.setBackground(Color.GREEN);
        BTN6.setText("");
        BTN6.setBackground(Color.GREEN);
        BTN7.setText("");
        BTN7.setBackground(Color.GREEN);
        BTN8.setText("");
        BTN8.setBackground(Color.GREEN);
        BTN9.setText("");
        BTN9.setBackground(Color.GREEN);
        BTN10.setText("");
        BTN10.setBackground(Color.GREEN);
        BTN11.setText("");
        BTN11.setBackground(Color.GREEN);
        BTN12.setText("");
        BTN12.setBackground(Color.GREEN);        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARMouseClicked

    private void CLEARActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_CLEARActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_CLEARActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(tictactoe.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new tictactoe().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTN1;
    private javax.swing.JButton BTN10;
    private javax.swing.JButton BTN11;
    private javax.swing.JButton BTN12;
    private javax.swing.JButton BTN2;
    private javax.swing.JButton BTN3;
    private javax.swing.JButton BTN4;
    private javax.swing.JButton BTN5;
    private javax.swing.JButton BTN6;
    private javax.swing.JButton BTN7;
    private javax.swing.JButton BTN8;
    private javax.swing.JButton BTN9;
    private javax.swing.JButton CLEAR;
    private javax.swing.JButton clearscore;
    private javax.swing.JToggleButton exit;
    private javax.swing.JLabel hours;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField lblplayer1score;
    private javax.swing.JTextField lblplayer2score;
    private javax.swing.JLabel millisecond;
    private javax.swing.JLabel minutes;
    private javax.swing.JButton newgame;
    private javax.swing.JLabel seconds;
    // End of variables declaration//GEN-END:variables

    public void Winner() {
   
 // code to be executed
 if((BTN1.getText().equals("X")) && (BTN2.getText().equals("X")) && (BTN3.getText().equals("X"))){
 JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
     p1score = p1score+1;
 lblplayer1score.setText(Integer.toString(p1score));
 }
 if((BTN4.getText().equals("X")) && (BTN5.getText().equals("X")) && (BTN6.getText().equals("X"))){
 JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
 p1score=p1score+1;
 lblplayer1score.setText(Integer.toString(p1score));
 }
if((BTN7.getText().equals("X")) && (BTN8.getText().equals("X")) && (BTN9.getText().equals("X"))){
 JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
 p1score=p1score+1;
 lblplayer1score.setText(Integer.toString(p1score));
 }
 if((BTN10.getText().equals("X")) && (BTN11.getText().equals("X")) && 
(BTN12.getText().equals("X"))){
 JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
 p1score=p1score+1;
 lblplayer1score.setText(Integer.toString(p1score));
 }
 if((BTN1.getText().equals("X")) && (BTN5.getText().equals("X")) && (BTN9.getText().equals("X"))){
 JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
 p1score=p1score+1;
 lblplayer1score.setText(Integer.toString(p1score));
 }
if((BTN4.getText().equals("X")) && (BTN8.getText().equals("X")) && (BTN12.getText().equals("X"))){
            JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
            p1score=p1score+1;
    lblplayer1score.setText(Integer.toString(p1score));
        }
    if((BTN3.getText().equals("X")) && (BTN5.getText().equals("X")) && (BTN7.getText().equals("X"))){
            JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
            p1score=p1score+1;
    lblplayer1score.setText(Integer.toString(p1score));
        }
    if((BTN6.getText().equals("X")) && (BTN8.getText().equals("X")) && (BTN10.getText().equals("X"))){
            JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
            p1score=p1score+1;
    lblplayer1score.setText(Integer.toString(p1score));
        }
    if((BTN1.getText().equals("X")) && (BTN4.getText().equals("X")) && (BTN7.getText().equals("X"))){
JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
p1score=p1score+1;
lblplayer1score.setText(Integer.toString(p1score));
}
if((BTN2.getText().equals("X")) && (BTN5.getText().equals("X")) && (BTN8.getText().equals("X"))){
JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
p1score=p1score+1;
lblplayer1score.setText(Integer.toString(p1score));
}
if((BTN3.getText().equals("X")) && (BTN6.getText().equals("X")) && (BTN9.getText().equals("X"))){
JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
p1score=p1score+1;
lblplayer1score.setText(Integer.toString(p1score));
}
  
if((BTN5.getText().equals("X")) && (BTN8.getText().equals("X")) && (BTN11.getText().equals("X"))){
JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
p1score=p1score+1;
lblplayer1score.setText(Integer.toString(p1score));
}
if((BTN6.getText().equals("X")) && (BTN9.getText().equals("X")) && (BTN12.getText().equals("X"))){
JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
p1score=p1score+1;
lblplayer1score.setText(Integer.toString(p1score));
}
if((BTN4.getText().equals("X")) && (BTN7.getText().equals("X")) && (BTN10.getText().equals("X"))){
JOptionPane.showMessageDialog(rootPane, "Player 1 Won", "Congratulations", 1);
p1score=p1score+1;
lblplayer1score.setText(Integer.toString(p1score));
}
   
   
   if((BTN1.getText().equals("O")) && (BTN2.getText().equals("O")) && (BTN3.getText().equals("O"))){
 JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
     p2score = p2score+1;
 lblplayer2score.setText(Integer.toString(p2score));
 }
 if((BTN4.getText().equals("O")) && (BTN5.getText().equals("O")) && (BTN6.getText().equals("O"))){
 JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
 p2score=p2score+1;
 lblplayer2score.setText(Integer.toString(p2score));
 }
if((BTN7.getText().equals("O")) && (BTN8.getText().equals("O")) && (BTN9.getText().equals("O"))){
 JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
 p2score=p2score+1;
 lblplayer2score.setText(Integer.toString(p2score));
 }
 if((BTN10.getText().equals("O")) && (BTN11.getText().equals("O")) && 
(BTN12.getText().equals("O"))){
 JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
 p2score=p2score+1;
 lblplayer2score.setText(Integer.toString(p2score));
 }
 if((BTN1.getText().equals("O")) && (BTN5.getText().equals("O")) && (BTN9.getText().equals("O"))){
 JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
 p2score=p2score+1;
 lblplayer2score.setText(Integer.toString(p2score));
 }
if((BTN4.getText().equals("O")) && (BTN8.getText().equals("O")) && (BTN12.getText().equals("O"))){
            JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
            p2score=p2score+1;
    lblplayer2score.setText(Integer.toString(p2score));
        }
    if((BTN3.getText().equals("O")) && (BTN5.getText().equals("O")) && (BTN7.getText().equals("O"))){
            JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
            p2score=p2score+1;
    lblplayer2score.setText(Integer.toString(p2score));
        }
    if((BTN6.getText().equals("O")) && (BTN8.getText().equals("O")) && (BTN10.getText().equals("O"))){
            JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
            p2score=p2score+1;
    lblplayer2score.setText(Integer.toString(p2score));
        }

    if((BTN1.getText().equals("O")) && (BTN4.getText().equals("O")) && (BTN7.getText().equals("O"))){
JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
p2score=p2score+1;
lblplayer2score.setText(Integer.toString(p2score));
}
if((BTN2.getText().equals("O")) && (BTN5.getText().equals("O")) && (BTN8.getText().equals("O"))){
JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
p2score=p2score+1;
lblplayer2score.setText(Integer.toString(p2score));
}
if((BTN3.getText().equals("O")) && (BTN6.getText().equals("O")) && (BTN9.getText().equals("O"))){
JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
p2score=p2score+1;
lblplayer2score.setText(Integer.toString(p2score));
}
  
if((BTN5.getText().equals("O")) && (BTN8.getText().equals("O")) && (BTN11.getText().equals("O"))){
JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
p2score=p2score+1;
lblplayer2score.setText(Integer.toString(p2score));
}
if((BTN6.getText().equals("O")) && (BTN9.getText().equals("O")) && (BTN12.getText().equals("O"))){
JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
p2score=p2score+1;
lblplayer2score.setText(Integer.toString(p2score));
}
if((BTN4.getText().equals("O")) && (BTN7.getText().equals("O")) && (BTN10.getText().equals("O"))){
JOptionPane.showMessageDialog(rootPane, "Player 2 Won", "Congratulations", 1);
p2score=p2score+1;
lblplayer2score.setText(Integer.toString(p2score));
    }
    }

    {
       
     state = true;
        
      Thread t  = new Thread(){
      
          public void run() {
         
             for(;;)
             {
                  if (state = true)
          {
      try
      {
          sleep(1);
          
            if (milliseconds>1000)
          {
          milliseconds=0;
          second++;
          }
          if (second>60)
          {
          second=0;
          minute++;
          }
           if (minute>60)
          {
          minute=0;
          hour++;
          }
          
           millisecond.setText("  " );
           milliseconds++;
           seconds.setText(" : "+ second);
            minutes.setText(" : "+ minute);
             hours.setText(""+ hour);
      }
      catch(Exception e)
              {
              
              }
          }
                  else 
                  {
                  break;
                  }
          }
          }
      };
      t.start();
    }                                      
    
    
    @Override
    public void enable() {
        super.enable(); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/OverriddenMethodBody
    }

    

        private static void setText(String toString) {
            // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
        }

}
